import { IMAGE_PATHS } from "../../../common/imageConstant"
export const products = [
    {
      id: 1,
      name: "High-Performance Brake Pads",
      category: "auto-parts",
      subcategory: "Brake Systems",
      brand: "Brembo",
      model: "BP-X1200",
      price: 49.99,
      originalPrice: 69.99,
      rating: 4.8,
      reviews: 156,
      image: IMAGE_PATHS.cartool,
      badge: "Best Seller",
      description: "Premium ceramic brake pads for superior stopping power",
      stock: 15,
      discount: 28,
      inStock: true,
      specifications: {
        material: "Ceramic",
        position: "Front",
        fitment: "Universal",
        warranty: "2 Years",
        dimensions: "12x8x4 inches",
        weight: "4.5 lbs",
      },
      features: ["Advanced ceramic formula", "Low dust production", "Quiet operation", "Extended pad life"],
      compatibility: ["Toyota Camry 2018-2023", "Honda Accord 2019-2023", "Nissan Altima 2020-2023"],
    },
    {
        id: 2,
        name: "High-Performance Brake Pads",
        category: "auto-parts",
        subcategory: "Brake Systems",
        brand: "Brembo",
        model: "BP-X1200",
        price: 49.99,
        originalPrice: 69.99,
        rating: 4.8,
        reviews: 156,
        image: IMAGE_PATHS.computer,
        badge: "Best Seller",
        description: "Premium ceramic brake pads for superior stopping power",
        stock: 15,
        discount: 28,
        inStock: true,
        specifications: {
          material: "Ceramic",
          position: "Front",
          fitment: "Universal",
          warranty: "2 Years",
          dimensions: "12x8x4 inches",
          weight: "4.5 lbs",
        },
        features: ["Advanced ceramic formula", "Low dust production", "Quiet operation", "Extended pad life"],
        compatibility: ["Toyota Camry 2018-2023", "Honda Accord 2019-2023", "Nissan Altima 2020-2023"],
      },
      {
        id: 3,
        name: "High-Performance Brake Pads",
        category: "auto-parts",
        subcategory: "Brake Systems",
        brand: "Brembo",
        model: "BP-X1200",
        price: 49.99,
        originalPrice: 69.99,
        rating: 4.8,
        reviews: 156,
        image: IMAGE_PATHS.computer2,
        badge: "Best Seller",
        description: "Premium ceramic brake pads for superior stopping power",
        stock: 15,
        discount: 28,
        inStock: true,
        specifications: {
          material: "Ceramic",
          position: "Front",
          fitment: "Universal",
          warranty: "2 Years",
          dimensions: "12x8x4 inches",
          weight: "4.5 lbs",
        },
        features: ["Advanced ceramic formula", "Low dust production", "Quiet operation", "Extended pad life"],
        compatibility: ["Toyota Camry 2018-2023", "Honda Accord 2019-2023", "Nissan Altima 2020-2023"],
      },
      {
        id: 4,
        name: "High-Performance Brake Pads",
        category: "auto-parts",
        subcategory: "Brake Systems",
        brand: "Brembo",
        model: "BP-X1200",
        price: 49.99,
        originalPrice: 69.99,
        rating: 4.8,
        reviews: 156,
        image: IMAGE_PATHS.vehicle,
        badge: "Best Seller",
        description: "Premium ceramic brake pads for superior stopping power",
        stock: 15,
        discount: 28,
        inStock: true,
        specifications: {
          material: "Ceramic",
          position: "Front",
          fitment: "Universal",
          warranty: "2 Years",
          dimensions: "12x8x4 inches",
          weight: "4.5 lbs",
        },
        features: ["Advanced ceramic formula", "Low dust production", "Quiet operation", "Extended pad life"],
        compatibility: ["Toyota Camry 2018-2023", "Honda Accord 2019-2023", "Nissan Altima 2020-2023"],
      },
  ];
  