export const paymentMethods = [
    { id: "credit-card", name: "Credit Card", types: ["Visa", "Mastercard", "American Express"] },
    { id: "debit-card", name: "Debit Card", types: ["Visa", "Mastercard"] },
    { id: "cash", name: "Cash on Delivery", types: [] },
    { id: "esewa", name: "Esewa", types: [] },
    { id: "net-banking", name: "Net Banking", types: [] },
    { id: "other", name: "Other", types: [] },
  ]
  
  export const paymentStatuses = [
    { id: "successful", name: "Successful", color: "green" },
    { id: "pending", name: "Pending", color: "yellow" },
    { id: "failed", name: "Failed", color: "red" },
    { id: "refunded", name: "Refunded", color: "blue" },
  ]
  
  export const sampleTransactions = [
    {
      id: "TXN001",
      orderId: "ORD123",
      customerName: "John Doe",
      customerEmail: "john.doe@example.com",
      paymentMethod: "Credit Card",
      paymentType: "Visa",
      amount: 250.0,
      date: "2025-03-09T14:30:00",
      status: "successful",
      items: [
        { name: "Engine Oil", quantity: 2, price: 29.99 },
        { name: "Oil Filter", quantity: 1, price: 12.99 },
        { name: "Brake Pads", quantity: 1, price: 89.99 },
        { name: "Wiper Blades", quantity: 2, price: 43.99 },
      ],
      shippingAddress: {
        street: "123 Main St",
        city: "New York",
        state: "NY",
        zip: "10001",
        country: "USA",
      },
      notes: "",
    },
    {
      id: "TXN002",
      orderId: "ORD124",
      customerName: "Jane Smith",
      customerEmail: "jane.smith@example.com",
      paymentMethod: "Esewa",
      paymentType: "",
      amount: 120.5,
      date: "2025-03-08T09:15:00",
      status: "pending",
      items: [
        { name: "Spark Plugs", quantity: 4, price: 15.99 },
        { name: "Air Filter", quantity: 1, price: 24.99 },
        { name: "Coolant", quantity: 1, price: 19.99 },
      ],
      shippingAddress: {
        street: "456 Oak Ave",
        city: "Boston",
        state: "MA",
        zip: "02108",
        country: "USA",
      },
      notes: "Customer requested express shipping",
    },
    {
      id: "TXN003",
      orderId: "ORD125",
      customerName: "Alex Brown",
      customerEmail: "alex.brown@example.com",
      paymentMethod: "Cash on Delivery",
      paymentType: "",
      amount: 75.0,
      date: "2025-03-07T16:45:00",
      status: "failed",
      items: [
        { name: "Headlight Bulbs", quantity: 2, price: 22.5 },
        { name: "Windshield Washer Fluid", quantity: 1, price: 8.99 },
        { name: "Car Wax", quantity: 1, price: 19.99 },
      ],
      shippingAddress: {
        street: "789 Pine Blvd",
        city: "Chicago",
        state: "IL",
        zip: "60007",
        country: "USA",
      },
      notes: "Customer not available at delivery time",
    },
    {
      id: "TXN004",
      orderId: "ORD126",
      customerName: "Emily Johnson",
      customerEmail: "emily.johnson@example.com",
      paymentMethod: "Credit Card",
      paymentType: "Mastercard",
      amount: 349.95,
      date: "2025-03-06T11:20:00",
      status: "refunded",
      items: [
        { name: "Car Battery", quantity: 1, price: 129.99 },
        { name: "Jump Starter", quantity: 1, price: 89.99 },
        { name: "Battery Charger", quantity: 1, price: 49.99 },
        { name: "Battery Terminal Cleaner", quantity: 1, price: 7.99 },
        { name: "Battery Cables", quantity: 1, price: 19.99 },
      ],
      shippingAddress: {
        street: "101 Maple Dr",
        city: "Seattle",
        state: "WA",
        zip: "98101",
        country: "USA",
      },
      notes: "Customer received defective battery",
    },
    {
      id: "TXN005",
      orderId: "ORD127",
      customerName: "Michael Wilson",
      customerEmail: "michael.wilson@example.com",
      paymentMethod: "Net Banking",
      paymentType: "",
      amount: 189.75,
      date: "2025-03-05T15:10:00",
      status: "successful",
      items: [
        { name: "Tire Pressure Gauge", quantity: 1, price: 12.99 },
        { name: "Floor Mats", quantity: 1, price: 59.99 },
        { name: "Car Cover", quantity: 1, price: 89.99 },
        { name: "Steering Wheel Cover", quantity: 1, price: 24.99 },
      ],
      shippingAddress: {
        street: "222 Cedar St",
        city: "Miami",
        state: "FL",
        zip: "33101",
        country: "USA",
      },
      notes: "",
    },
    {
      id: "TXN006",
      orderId: "ORD128",
      customerName: "Sarah Martinez",
      customerEmail: "sarah.martinez@example.com",
      paymentMethod: "Credit Card",
      paymentType: "American Express",
      amount: 425.5,
      date: "2025-03-04T10:05:00",
      status: "successful",
      items: [
        { name: "Car Stereo", quantity: 1, price: 299.99 },
        { name: "Speaker Set", quantity: 1, price: 89.99 },
        { name: "Installation Kit", quantity: 1, price: 35.99 },
      ],
      shippingAddress: {
        street: "333 Birch Ave",
        city: "Denver",
        state: "CO",
        zip: "80202",
        country: "USA",
      },
      notes: "",
    },
    {
      id: "TXN007",
      orderId: "ORD129",
      customerName: "David Lee",
      customerEmail: "david.lee@example.com",
      paymentMethod: "Esewa",
      paymentType: "",
      amount: 59.99,
      date: "2025-03-03T13:40:00",
      status: "successful",
      items: [
        { name: "Car Phone Mount", quantity: 1, price: 24.99 },
        { name: "USB Car Charger", quantity: 1, price: 14.99 },
        { name: "Charging Cable", quantity: 1, price: 9.99 },
        { name: "Car Air Freshener", quantity: 2, price: 4.99 },
      ],
      shippingAddress: {
        street: "444 Elm Ct",
        city: "Austin",
        state: "TX",
        zip: "78701",
        country: "USA",
      },
      notes: "",
    },
    {
      id: "TXN008",
      orderId: "ORD130",
      customerName: "Jennifer Garcia",
      customerEmail: "jennifer.garcia@example.com",
      paymentMethod: "Cash on Delivery",
      paymentType: "",
      amount: 149.95,
      date: "2025-03-02T17:25:00",
      status: "pending",
      items: [
        { name: "Dash Cam", quantity: 1, price: 99.99 },
        { name: "SD Card", quantity: 1, price: 19.99 },
        { name: "Dash Cam Mount", quantity: 1, price: 14.99 },
        { name: "Power Adapter", quantity: 1, price: 12.99 },
      ],
      shippingAddress: {
        street: "555 Spruce Rd",
        city: "San Francisco",
        state: "CA",
        zip: "94101",
        country: "USA",
      },
      notes: "Delivery scheduled for next week",
    },
  ]
  