export const sampleProducts = [
  {
    id: "1001",
    name: "Product 1001",
    category: "vehicle-parts",
    subcategory: "Engine",
    brand: "Toyota",
    model: "Model-2001",
    price: 299.99,
    originalPrice: 349.99,
    rating: 4.5,
    reviews: 128,
    image: "/placeholder.svg?height=500&width=500",
    description:
      "High-quality component for optimal performance. This premium product is designed to provide reliable and long-lasting service for your vehicle.",
    stock: 15,
    discount: 14,
    inStock: true,
    specifications: {
      Material: "Premium Alloy",
      Dimensions: "10 x 8 x 4 inches",
      Weight: "2.5 lbs",
      Warranty: "2 Years",
      Compatibility: "Most Toyota models 2015-2023",
      "Country of Origin": "Japan",
    },
    features: [
      "Enhanced durability",
      "Precision engineered",
      "Easy installation",
      "Improved performance",
      "Reduced noise",
    ],
    compatibility: ["Toyota Camry 2018-2023", "Toyota Corolla 2019-2023", "Toyota RAV4 2020-2023"],
    quantity: 2,
  },
  {
    id: "1002",
    name: "Product 1002",
    category: "vehicle-parts",
    subcategory: "Brakes",
    brand: "Brembo",
    model: "Model-2002",
    price: 149.99,
    originalPrice: 189.99,
    rating: 4.8,
    reviews: 95,
    image: "/placeholder.svg?height=500&width=500",
    description:
      "Premium brake system for superior stopping power. Engineered for performance and safety in all driving conditions.",
    stock: 22,
    discount: 21,
    inStock: true,
    specifications: {
      Material: "Ceramic Composite",
      Dimensions: "12 x 3 x 2 inches",
      Weight: "3.2 lbs",
      Warranty: "3 Years",
      Compatibility: "Multiple vehicle models",
      "Country of Origin": "Italy",
    },
    features: ["Superior stopping power", "Heat resistant", "Reduced brake dust", "Longer lifespan", "Quiet operation"],
    compatibility: ["Honda Civic 2017-2023", "Toyota Camry 2018-2023", "Ford F-150 2019-2023"],
    quantity: 1,
  },
  {
    id: "1003",
    name: "Product 1003",
    category: "vehicle-parts",
    subcategory: "Transmission",
    brand: "Honda",
    model: "Model-2003",
    price: 499.99,
    originalPrice: 599.99,
    rating: 4.7,
    reviews: 64,
    image: "/placeholder.svg?height=500&width=500",
    description:
      "Advanced transmission component for smooth gear shifts and improved fuel efficiency. Built to last with premium materials.",
    stock: 8,
    discount: 17,
    inStock: true,
    specifications: {
      Material: "High-grade Steel",
      Dimensions: "15 x 12 x 8 inches",
      Weight: "8.5 lbs",
      Warranty: "5 Years",
      Compatibility: "Honda vehicles 2016-2023",
      "Country of Origin": "Japan",
    },
    features: [
      "Smooth gear transitions",
      "Improved fuel efficiency",
      "Reduced vibration",
      "Enhanced durability",
      "OEM quality",
    ],
    compatibility: ["Honda Accord 2016-2023", "Honda Civic 2017-2023", "Honda CR-V 2018-2023"],
    quantity: 1,
  },
]

export const sampleAddresses = [
  {
    id: "addr-1",
    name: "John Doe",
    type: "home",
    street: "123 Main Street",
    city: "New York",
    state: "NY",
    zipCode: "10001",
    country: "USA",
    phone: "+1 (555) 123-4567",
    isDefault: true,
  },
  {
    id: "addr-2",
    name: "John Doe",
    type: "office",
    street: "456 Business Ave, Suite 200",
    city: "New York",
    state: "NY",
    zipCode: "10002",
    country: "USA",
    phone: "+1 (555) 987-6543",
    isDefault: false,
  },
]

export const shippingMethods = [
  {
    id: "shipping-1",
    name: "Standard Shipping",
    description: "Delivery in 3-5 business days",
    price: 0,
    estimatedDelivery: "Mar 15 - Mar 17, 2025",
  },
  {
    id: "shipping-2",
    name: "Express Delivery",
    description: "Delivery in 1-2 business days",
    price: 9.99,
    estimatedDelivery: "Mar 12 - Mar 13, 2025",
  },
  {
    id: "shipping-3",
    name: "Store Pickup",
    description: "Pick up at your nearest store",
    price: 0,
    estimatedDelivery: "Available tomorrow",
  },
]

export const paymentMethods = [
  {
    id: "payment-1",
    type: "card",
    name: "Credit Card",
    cardNumber: "**** **** **** 4567",
    cardType: "Visa",
    expiryDate: "09/27",
    isDefault: true,
  },
  {
    id: "khalti",
    name: "Khalti",
    type: "khalti",
    isDefault: false,
    // icon: "/path-to-khalti-logo.png", // optional icon path
  },
  {
    id: "payment-2",
    type: "wallet",
    name: "Digital Wallet",
    walletName: "PayPal",
    email: "john.doe@example.com",
    isDefault: false,
  },
  {
    id: "payment-3",
    type: "cod",
    name: "Cash on Delivery",
    description: "Pay when you receive your order",
    isDefault: false,
  },
]

export const availableCoupons = [
  {
    id: "coupon-1",
    code: "WELCOME10",
    description: "10% off your first order",
    discount: 10,
    type: "percentage",
  },
  {
    id: "coupon-2",
    code: "FREESHIP",
    description: "Free shipping on orders over $50",
    discount: 0,
    type: "free_shipping",
  },
  {
    id: "coupon-3",
    code: "PARTS20",
    description: "20% off all vehicle parts",
    discount: 20,
    type: "percentage",
    categories: ["vehicle-parts"],
  },
]

export const availableProducts = [
  {
    id: "1004",
    name: "Premium Brake Pads",
    category: "vehicle-parts",
    subcategory: "Brakes",
    brand: "StopTech",
    model: "ST-40",
    price: 89.99,
    originalPrice: 109.99,
    rating: 4.6,
    reviews: 78,
    image: "/placeholder.svg?height=500&width=500",
    description: "High-performance ceramic brake pads for superior stopping power and reduced brake dust.",
    stock: 25,
    discount: 18,
    inStock: true,
    specifications: {},
    features: [],
    compatibility: [],
    quantity: 1,
  },
  {
    id: "1005",
    name: "Air Filter System",
    category: "vehicle-parts",
    subcategory: "Air Intake",
    brand: "K&N",
    model: "KN-33",
    price: 59.99,
    originalPrice: 74.99,
    rating: 4.7,
    reviews: 112,
    image: "/placeholder.svg?height=500&width=500",
    description: "Performance air filter for increased airflow and engine efficiency.",
    stock: 18,
    discount: 20,
    inStock: true,
    specifications: {},
    features: [],
    compatibility: [],
    quantity: 1,
  },
  {
    id: "1006",
    name: "LED Headlight Kit",
    category: "vehicle-parts",
    subcategory: "Lighting",
    brand: "Philips",
    model: "X-treme Vision",
    price: 129.99,
    originalPrice: 159.99,
    rating: 4.8,
    reviews: 95,
    image: "/placeholder.svg?height=500&width=500",
    description: "Ultra-bright LED headlight kit for improved visibility and modern appearance.",
    stock: 12,
    discount: 19,
    inStock: true,
    specifications: {},
    features: [],
    compatibility: [],
    quantity: 1,
  },
]
