export const initialProducts = [
    {
      id: 1,
      name: "High-Performance Brake Pads",
      category: "auto-parts",
      subcategory: "Brake Systems",
      brand: "Brembo",
      model: "BP-X1200",
      price: 49.99,
      originalPrice: 69.99,
      rating: 4.8,
      reviews: 156,
      image: "/placeholder.svg?height=300&width=300",
      badge: "Best Seller",
      description: "Premium ceramic brake pads for superior stopping power",
      stock: 15,
      discount: 28,
      inStock: true,
      specifications: {
        material: "Ceramic",
        position: "Front",
        fitment: "Universal",
        warranty: "2 Years",
        dimensions: "12x8x4 inches",
        weight: "4.5 lbs",
      },
      features: ["Advanced ceramic formula", "Low dust production", "Quiet operation", "Extended pad life"],
      compatibility: ["Toyota Camry 2018-2023", "Honda Accord 2019-2023", "Nissan Altima 2020-2023"],
    },
    {
      id: 2,
      name: "NVIDIA RTX 4070 Graphics Card",
      category: "computer-parts",
      subcategory: "Graphics Cards",
      brand: "NVIDIA",
      model: "RTX 4070",
      price: 599.99,
      originalPrice: 649.99,
      rating: 4.9,
      reviews: 234,
      image: "/placeholder.svg?height=300&width=300",
      badge: "Hot Deal",
      description: "Next-gen gaming performance with ray tracing",
      stock: 8,
      discount: 8,
      inStock: true,
      specifications: {
        memory: "12GB GDDR6X",
        interface: "PCIe 4.0",
        ports: "HDMI 2.1, 3x DisplayPort 1.4a",
        powerRequirement: "650W",
        dimensions: "285x112x40mm",
        cooling: "Triple Fan",
      },
      features: ["Ray Tracing Cores", "DLSS 3.0", "4K Gaming", "Low Latency Mode"],
      compatibility: ["PCIe 4.0 Motherboards", "650W+ Power Supply", "Windows 10/11"],
    },
    {
      id: 3,
      name: "Premium Oil Filter Set",
      category: "auto-parts",
      subcategory: "Engine",
      brand: "Bosch",
      model: "OF-3200",
      price: 24.99,
      originalPrice: 34.99,
      rating: 4.7,
      reviews: 189,
      image: "/placeholder.svg?height=300&width=300",
      badge: "Top Rated",
      description: "Long-lasting protection for your engine",
      stock: 2,
      discount: 29,
      inStock: true,
      specifications: {
        material: "Synthetic Fiber",
        fitment: "Multiple Vehicles",
        warranty: "1 Year",
        dimensions: "3.5x3.5x4 inches",
        weight: "0.8 lbs",
      },
      features: [
        "High filtration efficiency",
        "Extended service life",
        "Easy installation",
        "Improved engine protection",
      ],
      compatibility: ["Most domestic and import vehicles"],
    },
    {
      id: 4,
      name: "Intel Core i7 13700K",
      category: "computer-parts",
      subcategory: "CPUs",
      brand: "Intel",
      model: "i7-13700K",
      price: 419.99,
      originalPrice: 449.99,
      rating: 4.9,
      reviews: 312,
      image: "/placeholder.svg?height=300&width=300",
      badge: "Popular",
      description: "Ultimate gaming and productivity performance",
      stock: 5,
      discount: 7,
      inStock: true,
      specifications: {
        cores: "16 (8P+8E)",
        threads: "24",
        baseFrequency: "3.4 GHz",
        boostFrequency: "5.4 GHz",
        socket: "LGA 1700",
        tdp: "125W",
      },
      features: ["Hybrid Architecture", "PCIe 5.0 Support", "DDR5 Memory Support", "Unlocked Multiplier"],
      compatibility: ["Intel 600/700 Series Motherboards", "DDR4/DDR5 Memory"],
    },
  ]
  