// Sample product categories
export const categories = [
    {
      id: "auto",
      name: "Auto Parts",
      subcategories: ["Engine Parts", "Brake Systems", "Transmission", "Electrical", "Suspension"],
    },
    { id: "computer", name: "Computer Parts", subcategories: ["GPU", "CPU", "Motherboard", "RAM", "Storage"] },
    { id: "tools", name: "Tools", subcategories: ["Hand Tools", "Power Tools", "Measurement", "Workshop"] },
  ]
  
  // Sample brands
  export const brands = [
    { id: "toyota", name: "Toyota", category: "auto" },
    { id: "brembo", name: "Brembo", category: "auto" },
    { id: "bosch", name: "Bosch", category: "auto" },
    { id: "msi", name: "MSI", category: "computer" },
    { id: "nvidia", name: "NVIDIA", category: "computer" },
    { id: "intel", name: "Intel", category: "computer" },
    { id: "dewalt", name: "DeWalt", category: "tools" },
    { id: "makita", name: "Makita", category: "tools" },
  ]
  
  // Sample warehouse locations
  export const warehouses = [
    { id: "wh1", name: "Main Warehouse" },
    { id: "wh2", name: "East Coast Facility" },
    { id: "wh3", name: "West Coast Facility" },
    { id: "wh4", name: "Central Distribution" },
  ]
  
  // Sample inventory data
  export const initialInventory = [
    {
      id: "P001",
      name: "Engine Oil",
      category: "Auto Parts",
      subcategory: "Engine Parts",
      brand: "Toyota",
      sku: "ENG-123",
      stockLevel: 50,
      minStockLevel: 10,
      status: "in-stock",
      warehouse: "wh1",
      price: 29.99,
      lastRestocked: "2025-03-01T10:30:00",
      supplier: "Auto Supplies Inc.",
      image: "/placeholder.svg?height=80&width=80",
    },
    {
      id: "P002",
      name: "Graphics Card RTX 4070",
      category: "Computer Parts",
      subcategory: "GPU",
      brand: "MSI",
      sku: "GPU-456",
      stockLevel: 5,
      minStockLevel: 8,
      status: "low-stock",
      warehouse: "wh2",
      price: 599.99,
      lastRestocked: "2025-02-15T14:45:00",
      supplier: "Tech Distributors LLC",
      image: "/placeholder.svg?height=80&width=80",
    },
    {
      id: "P003",
      name: "Brake Pads",
      category: "Auto Parts",
      subcategory: "Brake Systems",
      brand: "Brembo",
      sku: "BRK-789",
      stockLevel: 0,
      minStockLevel: 15,
      status: "out-of-stock",
      warehouse: "wh1",
      price: 89.99,
      lastRestocked: "2025-01-20T09:15:00",
      supplier: "Auto Supplies Inc.",
      image: "/placeholder.svg?height=80&width=80",
    },
    {
      id: "P004",
      name: "CPU Intel i9-13900K",
      category: "Computer Parts",
      subcategory: "CPU",
      brand: "Intel",
      sku: "CPU-101",
      stockLevel: 12,
      minStockLevel: 5,
      status: "in-stock",
      warehouse: "wh2",
      price: 499.99,
      lastRestocked: "2025-02-28T11:30:00",
      supplier: "Tech Distributors LLC",
      image: "/placeholder.svg?height=80&width=80",
    },
    {
      id: "P005",
      name: "Power Drill",
      category: "Tools",
      subcategory: "Power Tools",
      brand: "DeWalt",
      sku: "TLS-202",
      stockLevel: 8,
      minStockLevel: 10,
      status: "low-stock",
      warehouse: "wh3",
      price: 149.99,
      lastRestocked: "2025-02-10T13:45:00",
      supplier: "Tool World Inc.",
      image: "/placeholder.svg?height=80&width=80",
    },
    {
      id: "P006",
      name: "Transmission Fluid",
      category: "Auto Parts",
      subcategory: "Transmission",
      brand: "Toyota",
      sku: "TRN-303",
      stockLevel: 35,
      minStockLevel: 20,
      status: "in-stock",
      warehouse: "wh1",
      price: 19.99,
      lastRestocked: "2025-03-05T08:30:00",
      supplier: "Auto Supplies Inc.",
      image: "/placeholder.svg?height=80&width=80",
    },
    {
      id: "P007",
      name: "RAM 32GB DDR5",
      category: "Computer Parts",
      subcategory: "RAM",
      brand: "MSI",
      sku: "RAM-404",
      stockLevel: 0,
      minStockLevel: 10,
      status: "out-of-stock",
      warehouse: "wh4",
      price: 129.99,
      lastRestocked: "2025-01-15T10:15:00",
      supplier: "Tech Distributors LLC",
      image: "/placeholder.svg?height=80&width=80",
    },
    {
      id: "P008",
      name: "Wrench Set",
      category: "Tools",
      subcategory: "Hand Tools",
      brand: "Makita",
      sku: "TLS-505",
      stockLevel: 25,
      minStockLevel: 8,
      status: "in-stock",
      warehouse: "wh3",
      price: 59.99,
      lastRestocked: "2025-02-20T14:30:00",
      supplier: "Tool World Inc.",
      image: "/placeholder.svg?height=80&width=80",
    },
  ]
  