import { IMAGE_PATHS } from "../../../common/imageConstant"

export const newProducts = [
  {
    id: 1,
    name: "Next-Gen SSD 2TB",
    category: "Computer Parts",
    price: 199.99,
    timeAdded: "2 days ago",
    image: IMAGE_PATHS.car1,
    description: "Ultra-fast storage solution with PCIe 4.0",
    stock: 15,
    tags: ["New", "PCIe 4.0", "2TB"],
  },
  {
    id: 2,
    name: "LED Headlight Set",
    category: "Auto Parts",
    price: 129.99,
    timeAdded: "3 days ago",
    image: IMAGE_PATHS.cartool,
    description: "High-brightness LED headlight upgrade kit",
    stock: 8,
    tags: ["New", "LED", "Universal Fit"],
  },
  {
    id: 3,
    name: "DDR5 RAM 32GB Kit",
    category: "Computer Parts",
    price: 189.99,
    timeAdded: "4 days ago",
    image: IMAGE_PATHS.computer,
    description: "High-speed DDR5 memory for gaming",
    stock: 20,
    tags: ["New", "DDR5", "Dual Channel"],
  },
  {
    id: 4,
    name: "Performance Exhaust",
    category: "Auto Parts",
    price: 299.99,
    timeAdded: "5 days ago",
    image: IMAGE_PATHS.computer2,
    description: "Stainless steel performance exhaust system",
    stock: 5,
    tags: ["New", "Stainless Steel", "Sport"],
  },
  {
    id: 5,
    name: "Performance Exhaust",
    category: "Auto Parts",
    price: 299.99,
    timeAdded: "5 days ago",
    image: IMAGE_PATHS.image1,
    description: "Stainless steel performance exhaust system",
    stock: 5,
    tags: ["New", "Stainless Steel", "Sport"],
  },
  {
    id: 6,
    name: "Performance Exhaust",
    category: "Auto Parts",
    price: 299.99,
    timeAdded: "5 days ago",
    image: IMAGE_PATHS.image2,
    description: "Stainless steel performance exhaust system",
    stock: 5,
    tags: ["New", "Stainless Steel", "Sport"],
  },
]
